name: win-client
on:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  build:
    runs-on: windows-2025
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 1

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: 6.11.1
          arch: win64_msvc2022_64
          cache: true

      - name: Build x64 portable
        shell: cmd
        env:
          ML_SKIP_MSI: "1"
          QT_PATH: ${{ github.workspace }}\..\Qt\6.11.1\msvc2022_64\bin
        run: |
          set "PATH=%QT_ROOT_DIR%\bin;%QT_PATH%;%PATH%"
          where qmake
          scripts\build-arch.bat release

      - name: Upload portable
        uses: actions/upload-artifact@v4
        with:
          name: moonlight-extended-windows-x64
          path: build/installer-x64-release/MoonlightPortable-x64-*.zip
          if-no-files-found: error
